



all:
	@cd libft && make
	@cd parsing && make

re:
	@cd libft && make re
	@cd parsing && make re

clean:
	@cd libft && make clean
	@cd parsing && make clean

fclean:
	@cd libft && make fclean
	@cd parsing && make fclean

proper:
	@cd libft && make proper
	@cd parsing && make proper
